name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in cschad.com posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rssproxy.migor.org/api/tf?url=https%3A%2F%2Fcschad.com%2Fposts%2Findex.xml&re=full&debug=true&out=atom"
